version: '3'
services:
    pgsql:
        image: 'postgres:15.2-alpine'
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ryanpujo
            POSTGRES_PASSWORD: root
            POSTGRES_DB: rpcommerce

    testpg:
        image: 'postgres:15.2-alpine'
        ports:
            - 2000:5432
        environment:
            POSTGRES_USER: ryanpujo
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testing

